INSERT INTO food_localisation(food_id,locale_id,title) VALUES
(1,1,'Almond butter, creamy'),
(2,1,'Almond milk, refrigerated, unsweetened'),
(3,1,'Almond milk, unsweetened, plain, refrigerated'),
(4,1,'Almond milk, unsweetened, plain, shelf stable'),
(5,1,'Almonds dry roasted salted'),
(6,1,'Almonds, dry roasted, salted'),
(7,1,'Amaranth, flour'),
(8,1,'Apples, fuji'),
(9,1,'Apples, fuji, with skin, raw'),
(10,1,'Apples, gala'),
(11,1,'Apples, gala, with skin, raw'),
(12,1,'Apples, granny smith'),
(13,1,'Apples, granny smith, with skin, raw'),
(14,1,'Apples, honeycrisp'),
(15,1,'Apples, honeycrisp, with skin, raw'),
(16,1,'Apples, red delicious'),
(17,1,'Apples, red delicious, with skin, raw'),
(18,1,'Bacon'),
(19,1,'Bacon, cooked'),
(20,1,'Bananas, overripe'),
(21,1,'Bananas, overripe, medium size'),
(22,1,'Bananas, overripe, raw'),
(23,1,'Bananas, ripe'),
(24,1,'Bananas, ripe and slightly ripe, raw'),
(25,1,'Bananas, ripe, extra large size'),
(26,1,'Bananas, ripe, medium size'),
(27,1,'Bananas, ripe, medium size, dehydrated'),
(28,1,'Bananas, slightly ripe'),
(29,1,'Bananas, slightly ripe, medium size'),
(30,1,'Bananas, unripe, extra large size'),
(31,1,'Bananas, unripe, medium size'),
(32,1,'Barley, flour'),
(33,1,'Beans snap canned drained'),
(34,1,'Beans, black, canned, sodium added'),
(35,1,'Beans, black, canned, sodium added, drained and rinsed'),
(36,1,'Beans, blackeye pea, canned, sodium added'),
(37,1,'Beans, cannellini, canned, sodium added'),
(38,1,'Beans, cannellini, canned, sodium added, drained and rinsed'),
(39,1,'Beans, cannellini, dry'),
(40,1,'Beans, chick peas/garbanzos, canned, sodium added'),
(41,1,'Beans, chickpeas/garbanzos, dry'),
(42,1,'Beans, dry, black (0% moisture)'),
(43,1,'Beans, dry, brown (0% moisture)'),
(44,1,'Beans, dry, carioca (0% moisture)'),
(45,1,'Beans, dry, cranberry (0% moisture)'),
(46,1,'Beans, dry, dark red kidney (0% moisture)'),
(47,1,'Beans, dry, flor de mayo (0% moisture)'),
(48,1,'Beans, dry, great northern (0% moisture)'),
(49,1,'Beans, dry, light red kidney (0% moisture)'),
(50,1,'Beans, dry, light tan (0% moisture)'),
(51,1,'Beans, dry, medium red (0% moisture)'),
(52,1,'Beans, dry, navy (0% moisture)'),
(53,1,'Beans, dry, pink (0% moisture)'),
(54,1,'Beans, dry, pinto (0% moisture)'),
(55,1,'Beans, dry, red (0% moisture)'),
(56,1,'Beans, dry, small red (0% moisture)'),
(57,1,'Beans, dry, small white (0% moisture)'),
(58,1,'Beans, dry, tan (0% moisture)'),
(59,1,'Beans, great northern, canned, sodium added'),
(60,1,'Beans, great northern, canned, sodium added, drained and rinsed'),
(61,1,'Beans, kidney, dark red, canned, sodium added, sugar added'),
(62,1,'Beans, kidney, dark red, canned, sodium added, sugar added, drained and rinsed'),
(63,1,'Beans, kidney, light red, canned, sodium added, sugar added'),
(64,1,'Beans, kidney, light red, canned, sodium added, sugar added, drained and rinsed'),
(65,1,'Beans, navy, canned, sodium added'),
(66,1,'Beans, navy, canned, sodium added, drained and rinsed'),
(67,1,'Beans, pinto, canned, sodium added'),
(68,1,'Beans, pinto, canned, sodium added, drained and rinsed'),
(69,1,'Beans, snap, canned, drained, del monte'),
(70,1,'Beans, snap, green, canned, regular pack, drained solids'),
(71,1,'Beans, snap, green, raw'),
(72,1,'Beef, chuck, roast, boneless'),
(73,1,'Beef, flank steak'),
(74,1,'Beef, ground, 80% lean meat / 20% fat, raw'),
(75,1,'Beef, ground, 80% lean, 20% fat, raw'),
(76,1,'Beef, ground, 90% lean meat / 10% fat, raw'),
(77,1,'Beef, ground, 90% lean, 10% fat, raw'),
(78,1,'Beef, ground, grass-fed, 80% lean, 20% fat, raw'),
(79,1,'Beef, ground, grass-fed, 90% lean, 10% fat, raw'),
(80,1,'Beef, ribeye steak, boneless'),
(81,1,'Beef, top round, boneless'),
(82,1,'Blackeye pea, canned, sodium added, drained and rinsed'),
(83,1,'Blackeye pea, dry'),
(84,1,'Blueberries, fresh, raw'),
(85,1,'Blueberries, raw'),
(86,1,'Brazil nuts, raw'),
(87,1,'Broccoli, raw'),
(88,1,'Brown rice, long grain, unenriched'),
(89,1,'Buckwheat, flour'),
(90,1,'Buckwheat, whole grain'),
(91,1,'Butter, stick, salted'),
(92,1,'Butter, stick, unsalted'),
(93,1,'Buttermilk, low fat'),
(94,1,'Buttermilk, lowfat'),
(95,1,'Cabbage, green, raw'),
(96,1,'Cabbage, red, raw'),
(97,1,'Canola oil'),
(98,1,'Carrots, baby, raw'),
(99,1,'Carrots, baby, raw, peeled'),
(100,1,'Carrots, frozen, unprepared'),
(101,1,'Carrots, mature, raw'),
(102,1,'Cashews, raw'),
(103,1,'Cassava flour'),
(104,1,'Celery, raw'),
(105,1,'Cheese'),
(106,1,'Cheese, cheddar'),
(107,1,'Cheese, cotija, solid'),
(108,1,'Cheese, cottage, lowfat, 2% milkfat'),
(109,1,'Cheese, dry white, queso seco'),
(110,1,'Cheese, feta, whole milk, crumbled'),
(111,1,'Cheese, monterey jack, solid'),
(112,1,'Cheese, mozzarella, low moisture, part-skim'),
(113,1,'Cheese, oaxaca, solid'),
(114,1,'Cheese, parmesan, grated'),
(115,1,'Cheese, parmesan, grated, refrigerated'),
(116,1,'Cheese, provolone, sliced'),
(117,1,'Cheese, queso fresco, solid'),
(118,1,'Cheese, ricotta, whole milk'),
(119,1,'Cheese, ricotta, whole milk, lucerne'),
(120,1,'Cheese, swiss'),
(121,1,'Cherries, dark red, sweet, raw'),
(122,1,'Cherries, sweet, dark red, raw'),
(123,1,'Chestnut flour'),
(124,1,'Chicken, breast, boneless, skinless'),
(125,1,'Chicken, breast, boneless, skinless, raw'),
(126,1,'Chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, braised'),
(127,1,'Chicken, broilers or fryers, drumstick, meat only, cooked, braised'),
(128,1,'Chicken, ground, breast meat only, raw'),
(129,1,'Chicken, ground, raw'),
(130,1,'Chicken, ground, with additives, raw'),
(131,1,'Chicken, thigh, boneless, skinless, raw'),
(132,1,'Chicken, thighs, boneless, skinless'),
(133,1,'Chickpeas (garbanzo beans, bengal gram), canned, sodium added, drained and rinsed'),
(134,1,'Chickpeas, (garbanzo beans, bengal gram), dry'),
(135,1,'Coconut flour'),
(136,1,'Corn oil'),
(137,1,'Cotija (solid)'),
(138,1,'Cottage cheese, 4% milkfat, large curd'),
(139,1,'Cottage cheese, 4% milkfat, small curd'),
(140,1,'Cottage cheese, full fat, large or small curd'),
(141,1,'Cream cheese, block, full fat'),
(142,1,'Cream cheese, full fat, block'),
(143,1,'Cream, heavy'),
(144,1,'Cream, sour, full fat'),
(145,1,'Cucumber, with peel, raw'),
(146,1,'Cucumber, with skin, raw'),
(147,1,'Dennys - bacon'),
(148,1,'Dennys - ketchup'),
(149,1,'Dried egg yolk (without free-flow agent added)'),
(150,1,'Dried stabilized egg white'),
(151,1,'Dried whole egg (without free-flow agent added)'),
(152,1,'Egg whites'),
(153,1,'Egg whites dried'),
(154,1,'Egg whites, dried'),
(155,1,'Egg yolk'),
(156,1,'Egg yolks dried'),
(157,1,'Egg yolks, dried'),
(158,1,'Egg, grade a, large, white, raw, fresh'),
(159,1,'Egg, grade a, large, whole, raw, fresh'),
(160,1,'Egg, grade a, large, yolk, raw, fresh'),
(161,1,'Egg, white, dried'),
(162,1,'Egg, white, raw, frozen, pasteurized'),
(163,1,'Egg, whole, dried'),
(164,1,'Egg, whole, raw, frozen, pasteurized'),
(165,1,'Egg, yolk, dried'),
(166,1,'Egg, yolk, raw, frozen, pasteurized'),
(167,1,'Eggs, grade a, large'),
(168,1,'Eggs, grade a, large, egg white'),
(169,1,'Eggs, grade a, large, egg whole'),
(170,1,'Eggs, grade a, large, egg yolk'),
(171,1,'Eggs, whites'),
(172,1,'Eggs, whole'),
(173,1,'Eggs, yolk'),
(174,1,'Figs, dried, uncooked'),
(175,1,'Fish, haddock, raw'),
(176,1,'Fish, pollock, raw'),
(177,1,'Fish, tuna, light, canned in water, drained solids'),
(178,1,'Flaxseed, ground'),
(179,1,'Flour, 00'),
(180,1,'Flour, all-purpose, enriched'),
(181,1,'Flour, all-purpose, unenriched'),
(182,1,'Flour, almond'),
(183,1,'Flour, almond, blanched'),
(184,1,'Flour, amaranth'),
(185,1,'Flour, barley'),
(186,1,'Flour, bread, white, enriched'),
(187,1,'Flour, bread, white, enriched, unbleached'),
(188,1,'Flour, buckwheat'),
(189,1,'Flour, cassava'),
(190,1,'Flour, chestnut'),
(191,1,'Flour, coconut'),
(192,1,'Flour, corn, enriched'),
(193,1,'Flour, corn, yellow, fine meal, enriched'),
(194,1,'Flour, oat, whole grain'),
(195,1,'Flour, pastry, unenriched, unbleached'),
(196,1,'Flour, potato'),
(197,1,'Flour, quinoa'),
(198,1,'Flour, rice, brown'),
(199,1,'Flour, rice, glutenous'),
(200,1,'Flour, rice, glutinous'),
(201,1,'Flour, rice, white'),
(202,1,'Flour, rice, white, unenriched'),
(203,1,'Flour, rye'),
(204,1,'Flour, semolina, coarse'),
(205,1,'Flour, semolina, coarse and semi-coarse'),
(206,1,'Flour, semolina, fine'),
(207,1,'Flour, semolina, semi-coarse'),
(208,1,'Flour, sorghum'),
(209,1,'Flour, soy, defatted'),
(210,1,'Flour, soy, full fat'),
(211,1,'Flour, soy, full-fat'),
(212,1,'Flour, spelt, whole grain'),
(213,1,'Flour, wheat, all-purpose, enriched, bleached'),
(214,1,'Flour, wheat, all-purpose, enriched, unbleached'),
(215,1,'Flour, wheat, all-purpose, unenriched, unbleached'),
(216,1,'Flour, whole grain oat'),
(217,1,'Flour, whole wheat, unenriched'),
(218,1,'Frankfurter, beef, unheated'),
(219,1,'Garlic'),
(220,1,'Garlic, raw'),
(221,1,'Grapes, green, seedless, fresh, raw'),
(222,1,'Grapes, green, seedless, raw'),
(223,1,'Grapes, red, seedless, fresh, raw'),
(224,1,'Grapes, red, seedless, raw'),
(225,1,'Green beans, raw'),
(226,1,'Ground flaxseed meal'),
(227,1,'Hazelnuts, raw'),
(228,1,'Heavy cream'),
(229,1,'Hummus'),
(230,1,'Hummus, other'),
(231,1,'Hummus, sabra classic'),
(232,1,'Hummus, tribe classic'),
(233,1,'Kale'),
(234,1,'Kale, fresh, unprepared'),
(235,1,'Kale, frozen, as purchased'),
(236,1,'Kale, frozen, cooked'),
(237,1,'Kale, frozen, cooked, boiled, drained, without salt'),
(238,1,'Kale, raw'),
(239,1,'Ketchup'),
(240,1,'Kiwifruit, green, raw'),
(241,1,'Lentils, brown, dry'),
(242,1,'Lentils, dry'),
(243,1,'Lettuce, cos or romaine, raw'),
(244,1,'Lettuce, iceberg, raw'),
(245,1,'Lettuce, leaf, green, raw'),
(246,1,'Lettuce, leaf, red, raw'),
(247,1,'Lettuce, romaine, green, raw'),
(248,1,'Liquid egg white (without whipping agents)'),
(249,1,'Liquid egg yolk (plain, no salt or sugar)'),
(250,1,'Liquid whole egg (plain, no salt or sugar)'),
(251,1,'Lunchmeat ham'),
(252,1,'Macadamia nuts, raw'),
(253,1,'Melons, cantaloupe, raw'),
(254,1,'Milk, 1%'),
(255,1,'Milk, 2%'),
(256,1,'Milk, skim'),
(257,1,'Milk, whole'),
(258,1,'Millet, whole grain'),
(259,1,'Monterey jack cheese, block'),
(260,1,'Mushroom, beech'),
(261,1,'Mushroom, crimini'),
(262,1,'Mushroom, enoki'),
(263,1,'Mushroom, king oyster'),
(264,1,'Mushroom, lion''s mane'),
(265,1,'Mushroom, maitake'),
(266,1,'Mushroom, oyster'),
(267,1,'Mushroom, pioppini'),
(268,1,'Mushroom, portabella'),
(269,1,'Mushrooms, crimini'),
(270,1,'Mushrooms, enoki'),
(271,1,'Mushrooms, hon-shimiji (beech), white'),
(272,1,'Mushrooms, king oyster'),
(273,1,'Mushrooms, lion''s mane'),
(274,1,'Mushrooms, lions mane'),
(275,1,'Mushrooms, maitake'),
(276,1,'Mushrooms, oyster'),
(277,1,'Mushrooms, pioppini'),
(278,1,'Mushrooms, portabella'),
(279,1,'Mushrooms, shiitake'),
(280,1,'Mushrooms, white button'),
(281,1,'Mustard, prepared, yellow'),
(282,1,'Nectarines, raw'),
(283,1,'Nuts, almonds, dry roasted, with salt added'),
(284,1,'Nuts, almonds, raw, whole'),
(285,1,'Nuts, almonds, whole, raw'),
(286,1,'Nuts, brazilnuts, raw'),
(287,1,'Nuts, cashew nuts, raw'),
(288,1,'Nuts, hazelnuts or filberts, raw'),
(289,1,'Nuts, macadamia nuts, raw'),
(290,1,'Nuts, pecans, halves, raw'),
(291,1,'Nuts, pecans, raw, halves'),
(292,1,'Nuts, pine nuts, raw'),
(293,1,'Nuts, pistachio nuts, raw'),
(294,1,'Nuts, walnuts, english, halves, raw'),
(295,1,'Nuts, walnuts, english, raw, halves'),
(296,1,'Oat milk, refrigerated, unsweetened'),
(297,1,'Oat milk, unsweetened, plain, refrigerated'),
(298,1,'Oats, whole grain, rolled, old fashioned'),
(299,1,'Oats, whole grain, steel cut'),
(300,1,'Oaxaca'),
(301,1,'Oil, canola'),
(302,1,'Oil, coconut'),
(303,1,'Oil, corn'),
(304,1,'Oil, olive, extra light'),
(305,1,'Oil, olive, extra virgin'),
(306,1,'Oil, peanut'),
(307,1,'Oil, safflower'),
(308,1,'Oil, soybean'),
(309,1,'Oil, sunflower'),
(310,1,'Olive oil control composite'),
(311,1,'Olive oil, extra virgin'),
(312,1,'Olives green stuffed with pimentos'),
(313,1,'Olives, green manzanilla stuffed with pimentos, lindsay'),
(314,1,'Olives, green manzanilla stuffed with pimentos, mario'),
(315,1,'Olives, green manzanilla stuffed with pimentos, roland'),
(316,1,'Olives, green manzanilla stuffed with pimentos, star'),
(317,1,'Olives, green, manzanilla, stuffed with pimiento'),
(318,1,'Olives, green, stuffed with pimentos'),
(319,1,'Onion rings, breaded, par fried, frozen, prepared, heated in oven'),
(320,1,'Onions, red'),
(321,1,'Onions, red, raw'),
(322,1,'Onions, white'),
(323,1,'Onions, white, raw'),
(324,1,'Onions, yellow'),
(325,1,'Onions, yellow, raw'),
(326,1,'Oranges, raw, navels'),
(327,1,'Panera - bacon'),
(328,1,'Panera - ham'),
(329,1,'Panera bacon turkey bravo'),
(330,1,'Peaches, yellow, raw'),
(331,1,'Peanut butter, creamy'),
(332,1,'Peanut butter, smooth style, with salt'),
(333,1,'Peanuts, raw'),
(334,1,'Pears, raw, bartlett'),
(335,1,'Peas, green, sweet, canned, sodium added, sugar added'),
(336,1,'Peas, green, sweet, canned, sodium added, sugar added, drained and rinsed'),
(337,1,'Peppers, bell, green, raw'),
(338,1,'Peppers, bell, orange, raw'),
(339,1,'Peppers, bell, orange, raw, mini'),
(340,1,'Peppers, bell, red, raw'),
(341,1,'Peppers, bell, red, raw, mini'),
(342,1,'Peppers, bell, yellow, raw'),
(343,1,'Peppers, bell, yellow, raw, mini'),
(344,1,'Pickles, cucumber, dill or kosher dill'),
(345,1,'Pickles, kosher dill'),
(346,1,'Pickles, kosher, dill, spears, claussen'),
(347,1,'Pickles, kosher, dill, spears, mt. olive'),
(348,1,'Pickles, kosher, dill, spears, other'),
(349,1,'Pickles, kosher, dill, spears, vlasic'),
(350,1,'Pineapple, raw'),
(351,1,'Pistachio nuts, raw'),
(352,1,'Pork, ground, raw'),
(353,1,'Pork, loin, boneless'),
(354,1,'Pork, loin, boneless, raw'),
(355,1,'Pork, loin, tenderloin, boneless, raw'),
(356,1,'Pork, tenderloin, boneless'),
(357,1,'Potatoes, gold, without skin, raw'),
(358,1,'Potatoes, red, without skin, raw'),
(359,1,'Potatoes, russet, without skin, raw'),
(360,1,'Provolone cheese, sliced, non-smoked'),
(361,1,'Provolone cheese, sliced, smoked'),
(362,1,'Pumpkin seeds (pepitas), raw'),
(363,1,'Quinoa, flour'),
(364,1,'Raspberries, fresh, raw'),
(365,1,'Raspberries, raw'),
(366,1,'Rice, brown, long grain, unenriched, raw'),
(367,1,'Rice, white, long grain, unenriched, raw'),
(368,1,'Ricotta cheese, whole milk'),
(369,1,'Rye, flour'),
(370,1,'Salsa'),
(371,1,'Salsa, pace chunky - medium'),
(372,1,'Salsa, tostitos chunky - medium'),
(373,1,'Salt, essential everyday, iodized'),
(374,1,'Salt, food club, iodized'),
(375,1,'Salt, heb iodized'),
(376,1,'Salt, hy vee, iodized'),
(377,1,'Salt, iodized'),
(378,1,'Salt, laura lynn, iodized'),
(379,1,'Salt, morton, iodized'),
(380,1,'Salt, not iodized'),
(381,1,'Salt, table, iodized'),
(382,1,'Sauce, pasta, spaghetti/marinara, ready-to-serve'),
(383,1,'Sauce, salsa, ready-to-serve'),
(384,1,'Seeds, pumpkin seeds (pepitas), raw'),
(385,1,'Seeds, sunflower seed kernels, dry roasted, with salt added'),
(386,1,'Seeds, sunflower seed, kernel, raw'),
(387,1,'Sesame butter, creamy'),
(388,1,'Sesame seed butter (tahini), creamy'),
(389,1,'Sorghum, flour'),
(390,1,'Sour cream, full fat'),
(391,1,'Soy milk, refrigerated, sweetened'),
(392,1,'Soy milk, sweetened, plain, refrigerated'),
(393,1,'Soy milk, unsweetened, plain, shelf stable'),
(394,1,'Soybean oil'),
(395,1,'Spinach, baby'),
(396,1,'Spinach, mature'),
(397,1,'Spinach, regular (mature)'),
(398,1,'Strawberries, fresh, raw'),
(399,1,'Strawberries, raw'),
(400,1,'Subway - bacon'),
(401,1,'Subway - ham'),
(402,1,'Sunflower seed kernels, raw'),
(403,1,'Sunflower seeds dry roasted salted'),
(404,1,'Sunflower seeds, dry roasted, salted'),
(405,1,'Sunflower seeds, dry roasted, salted, planters'),
(406,1,'Sweet potatoes, orange flesh, without skin, raw'),
(407,1,'Tomato, roma'),
(408,1,'Tomatoes, canned'),
(409,1,'Tomatoes, canned, diced, del monte'),
(410,1,'Tomatoes, canned, diced, hunts'),
(411,1,'Tomatoes, canned, red, ripe, diced'),
(412,1,'Tomatoes, grape'),
(413,1,'Tomatoes, grape, raw'),
(414,1,'Tomatoes, roma'),
(415,1,'Tuna, bumble bee chunk light in water, drained solids'),
(416,1,'Tuna, chicken of the sea chunk light, in water, drained solids'),
(417,1,'Tuna, chicken of the sea, chunk light, in water, drained solids'),
(418,1,'Tuna, chunk light, canned in water, drained solids'),
(419,1,'Tuna, starkist chunk light, in water, drained solids'),
(420,1,'Tuna, starkist, chunk light, in water, drained solids'),
(421,1,'Turkey, ground, 93% lean, 7% fat, pan-broiled crumbles'),
(422,1,'Turkey, ground, 93% lean, 7% fat, raw'),
(423,1,'Turkey, ground, 93% lean/ 7% fat, raw'),
(424,1,'Vegetable oil (100% soybean oil)'),
(425,1,'White rice, long grain, unenriched'),
(426,1,'Whole eggs'),
(427,1,'Whole eggs dried'),
(428,1,'Whole eggs, dried'),
(429,1,'Yogurt, greek, plain, nonfat'),
(430,1,'Yogurt, greek, plain, whole milk'),
(431,1,'Yogurt, greek, strawberry, nonfat'),
(432,1,'Yogurt, greek, whole milk, plain'),
(433,1,'Yogurt, plain, nonfat'),
(434,1,'Yogurt, plain, whole milk'),
(435,1,'Yogurt, whole milk, plain')
