CREATE TABLE IF NOT EXISTS user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	password_hashed TEXT NOT NULL,
    locale_id INTEGER NOT NULL,
	FOREIGN KEY (locale_id) REFERENCES locale(id),
    UNIQUE (name)
) STRICT
