CREATE TABLE IF NOT EXISTS consumption_log (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	food_id INTEGER NOT NULL,
    user_id INTERGER NOT NULL,
	mass REAL NOT NULL,
	consumed_at TEXT NOT NULL,
	FOREIGN KEY (food_id) REFERENCES food(id) ON DELETE CASCADE
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) STRICT
